
# <font color="red"> Cuaderno 2. Compilación y entrenamiento de modelos en  Tensorflow  y Keras. </font>

## <font color="blue"> Por Alfredo Alfredo Diaz </font>

![image](https://github.com/adiacla/bigdata/blob/master/Keras-vs-TensorFlow-vs-PyTorch.jpg?raw=true)

**Keras**

Keras es una librería escrita en Python, diseñada específicamente para hacer experimentos con redes neuronales. Permite crear prototipos rápidamente y de manera fácil, pues está pensada para que sea fácil de usar.

Tener la posibilidad de pasar de una idea a un resultado con el mínimo retraso posible es clave cuando haces investigación.

**Pytorch**

Pytorch es un framework de Python que permite el crecimiento rápido del Deep Learning, con una fuerte aceleración de la GPU. La característica principal de Pytorch es que utiliza grafos computacionales dinámicos. Todos los frameworks de Deep Learning utilizan un lenguaje, como Python en este caso, y un grafo computacional. Esto funciona así por cuestiones de eficiencia y optimización, pues un grafo computacional corre en paralelo en la GPU.


**TensorFlow**

Cuando una red neuronal se vuelve más compleja, llena de capas y parámetros, el proceso se vuelve mucho más complejo. Es aquí donde entra TensorFlow, una librería de computación numérica que computa gradientes automáticamente, esto quiere decir que está a un nivel más bajo y profundo que Keras o Pytorch.

TensorFlow fue desarrollada por Google y la utilizan empresas como Airbnb, Dropbox, Uber y Snapchat. Aunque es muy popular es más recomendable para proyectos grandes y quizás más complejos, pues te da mucho control cuando estás construyendo redes neuronales.

Si quieres aprender a diseñar redes neuronales y crear prototipos de manera rápida para entender cómo funcionan, una librería como Keras es ideal, pues incluso ésta utiliza TensorFlow por debajo para computar gradientes, pero sin que tengas que involucrarte con eso. Pytorch combina las dos cosas, pues te ayuda a construir las redes y computa los gradientes automáticamente.

**Scikit-learn**

Otra librería ideal para diseñar y entrenar redes neuronales es Scikit-learn, que también está escrita en Python y que utilizan empresas como Spotify, Booking y Evernote. Emplea algoritmos de clasificación (determina a qué categoría pertenece un objeto), regresión (asocia atributos de valor continuo a objetos) y agrupamiento (agrupa objetos similares en conjuntos); y opera de manera simultánea con librerías como NumPy y SciPy.

**Librerías de Python relacionadas con Redes Neuronales**

![imagen](https://aitalks.es/wp-content/uploads/2020/06/Portada-librerias-python.jpg)

#Tensorflow

**Instalación y Configuración**
Antes de comenzar, asegúrate de tener Python instalado en tu máquina. Para instalar TensorFlow, ejecuta el siguiente comando:

      pip install tensorflow


Si está usando google colab ya tienes instalado tensorflow y keras, si estas usando tu ambiente propio, recomendamos instalar TensorFlow en un entorno virtual para evitar conflictos con otras librerías. Para crear y activar un entorno virtual, usa:

    # Crear entorno virtual
    python -m venv tf_env

    # Activar el entorno (Windows)
    tf_env\Scripts\activate

    # Activar el entorno (Mac/Linux)
    source tf_env/bin/activate

TensorFlow opera principalmente con arreglos multidimensionales llamados tensores, que son la base de cualquier modelo de aprendizaje automático. Estos tensores son similares a matrices y arrays de bibliotecas como NumPy, pero ofrecen capacidades adicionales, como la ejecución en hardware especializado como GPU.

Un tensor tiene dos atributos principales que debemos comprender:

* shape: Describe la dimensión del tensor a lo largo de cada uno de sus ejes.
* dtype: Especifica el tipo de datos que contiene, como float32, int32, etc.

Vamos a ir trabajando con tensorflow para crear y trabajar con tensores

In [1]:
!python -V

Python 3.12.12


In [2]:
import tensorflow as tf
print(tf.__version__)
#Es importante usar la misma versión del tensorflow cuando se entrena y se despliegua.

2.19.0


In [3]:
#listar las librerias instaladas que son tensorflow
!pip list | grep tensorflow

tensorflow                               2.19.0
tensorflow-datasets                      4.9.9
tensorflow_decision_forests              1.12.0
tensorflow-hub                           0.16.1
tensorflow-metadata                      1.17.3
tensorflow-probability                   0.25.0
tensorflow-text                          2.19.0


In [4]:
#listar librerias keras
!pip list | grep keras

keras                                    3.10.0
keras-hub                                0.21.1
keras-nlp                                0.21.1
tf_keras                                 2.19.0


In [5]:
#listar librerias pytorch
!pip list | grep torch

torch                                    2.9.0+cu128
torchao                                  0.10.0
torchaudio                               2.9.0+cu128
torchcodec                               0.8.0+cu128
torchdata                                0.11.0
torchsummary                             1.5.1
torchtune                                0.6.1
torchvision                              0.24.0+cu128


In [13]:
!nvidia-smi

Thu Feb 19 00:54:38 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   58C    P0             28W /   70W |     107MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

##Operaciones Básicas con TensorFlow

Una de las principales características de TensorFlow es su capacidad para realizar cálculos con tensores, que son estructuras de datos similares a matrices o arrays. A continuación, veremos cómo crear tensores básicos y realizar operaciones matemáticas:

In [7]:
import tensorflow as tf

# Crear un tensor bidimensional
x = tf.constant([[1., 2., 3.],
                 [4., 5., 6.]])

# Mostrar el tensor, su forma y tipo de datos
print("Tensor:\n", x)
print("Forma:", x.shape)
print("Tipo de datos:", x.dtype)
print("Tipo de tensor", type(x))

Tensor:
 tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
Forma: (2, 3)
Tipo de datos: <dtype: 'float32'>
Tipo de tensor <class 'tensorflow.python.framework.ops.EagerTensor'>


In [8]:
x.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [9]:
import numpy as np
arreglo=np.array([[1,2,3],[4,5,6]])
type(arreglo)

numpy.ndarray

##Operaciones Matemáticas con Tensores

TensorFlow permite realizar operaciones estándar sobre tensores, además de operaciones especializadas en aprendizaje automático. Veamos algunos ejemplos básicos:

In [10]:
# Operaciones aritméticas
print("Suma de tensores:\n", x + x)
print("-"*80,"\n")

Suma de tensores:
 tf.Tensor(
[[ 2.  4.  6.]
 [ 8. 10. 12.]], shape=(2, 3), dtype=float32)
-------------------------------------------------------------------------------- 



In [11]:
print("Resta de tensores:\n", x - x)
print("-"*80,"\n")

Resta de tensores:
 tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
-------------------------------------------------------------------------------- 



In [12]:
print("Multiplicación por escalar:\n", 5 * x,"\n")
print("-"*80,"\n")

Multiplicación por escalar:
 tf.Tensor(
[[ 5. 10. 15.]
 [20. 25. 30.]], shape=(2, 3), dtype=float32) 

-------------------------------------------------------------------------------- 



In [14]:
# LA transpuesta
resultado = tf.transpose(x)
print("Producto matricial:\n", resultado,"\n")
print("-"*80,"\n")

Producto matricial:
 tf.Tensor(
[[1. 4.]
 [2. 5.]
 [3. 6.]], shape=(3, 2), dtype=float32) 

-------------------------------------------------------------------------------- 



In [15]:
# Producto matricial (operador '@')
resultado = x @ tf.transpose(x)
print("Producto matricial:\n", resultado,"\n")
print("-"*80,"\n")

Producto matricial:
 tf.Tensor(
[[14. 32.]
 [32. 77.]], shape=(2, 2), dtype=float32) 

-------------------------------------------------------------------------------- 



In [15]:
# Concatenación de tensores
concatenado = tf.concat([x, x, x], axis=0)
print("Tensor concatenado:\n", concatenado,"\n")
print("-"*80,"\n")


In [16]:
#concatenar x, con x**2, X**3, por las columnas
concatenado = tf.concat([x, x**2, x**3], axis=1)
print("Tensor concatenado:\n", concatenado,"\n")
print("-"*80,"\n")

In [17]:
x

In [18]:
#media por sample
media = tf.reduce_mean(x, axis=1)
print("Media por sample:\n", media,"\n")
print("-"*80,"\n")

In [19]:
# Media por feature (columna)
mean_features = tf.reduce_mean(x, axis=0)
print("Media por feature:", mean_features.numpy())

In [20]:
#crear el tensor lalamdo "tensor" de [[1.,4.,0.5,2],[2.,3.,1.,0.],[2.,4.,1.,2.]]
tensor=tf.constant([[1.,4.,0.5,2],[2.,3.,1.,0.],[2.,4.,1.,2.]])
print("Tensor:\n", tensor)

In [21]:
tensorr=tensor**(0.5)
print("Tensor:\n", tensorr)

In [22]:
tensorsuma=tensor+tensorr
print("Tensor:\n", tensorsuma)

In [23]:
tensorcon=tf.concat([tensor,tensorr,tensorsuma],axis=0)
print("Tensor:\n", tensorcon)

In [24]:
respuesta=tf.concat([(tensorcon,tensorcon)],axis=1)
print("Tensor:\n", respuesta)

In [25]:
tensorcon

In [26]:
sumah=tf.reduce_sum(tensorcon,axis=1)
print("Tensor:\n", sumah)

In [27]:
mediah=tf.reduce_mean(tensorcon,axis=1)
print("Tensor:\n", mediah)

In [ ]:
sumav=tf.reduce_sum(tensorcon,axis=0)
print("Tensor:\n", sumav)

In [29]:
mediav=tf.reduce_mean(tensorcon,axis=0)
print("Tensor:\n", mediav)

# Concepto de sigmoide y softmax

![](https://www.researchgate.net/publication/325856086/figure/fig1/AS:723221292789765@1549440801787/Softmax-function-image.png)


# Softmax explicado paso a paso

##  ¿Qué es Softmax?

Softmax es una función que transforma un vector de números reales en un vector de **probabilidades** que suman 1.  
Se usa mucho en **clasificación multiclase**, porque permite interpretar las salidas de un modelo como probabilidades de cada clase.  

Si tienes un vector $(z = [z_1, z_2, ..., z_n])$, el Softmax se define así:

$sigma(z_i) = \frac{e^{z_i}}{\sum_{j=1}^{n} e^{z_j}}$


Donde:

- $(e^{z_i})$ es la exponencial de cada elemento.
- El denominador $(\sum_{j=1}^{n} e^{z_j})$ normaliza para que la suma sea 1.

---

## 2 Ejemplo paso a paso

Supongamos que tenemos un vector:


$z = [2.0, 1.0, 0.1]$


**Paso 1: Calcular la exponencial de cada elemento**

$e^z = [e^2.0, e^1.0, e^{0.1}] \approx [7.389, 2.718, 1.105]$


**Paso 2: Sumar todas las exponenciales**
${suma} = 7.389 + 2.718 + 1.105 \approx 11.212$


**Paso 3: Dividir cada exponencial por la suma**

${Softmax}(z) = \left[\frac{7.389}{11.212}, \frac{2.718}{11.212}, \frac{1.105}{11.212}\right] \approx [0.659, 0.242, 0.099]$

 Ahora tenemos un vector de **probabilidades** que suman 1.

---


In [30]:
x

In [31]:
# Aplicación de una función matemática: Softmax
softmax = tf.nn.softmax(x, axis=1)
print("Softmax aplicado al tensor:\n", softmax,"\n")
print("-"*80,"\n")

In [32]:

# Reducción: suma total de los elementos del tensor
suma_total = tf.reduce_sum(x)
print("Suma total del tensor:", suma_total.numpy())
suma_total

##Ejecución en GPU
TensorFlow puede aprovechar GPUs para acelerar los cálculos.

Si está usando Google Colab, vaya a menu a ***Entorno de ejecución ***y luego ingrese a ***Cambiar tipo de Entorno de Ejecución*** y luego seleccione ***T4 GPU ***. Debe ejecutar todas las celdas anteriores.


Verifica si tu sistema está utilizando una GPU con este código:


In [33]:
if tf.config.list_physical_devices('GPU'):
    print("TensorFlow está utilizando la GPU")
else:
    print("TensorFlow no está utilizando la GPU")

##Variables en TensorFlow
Mientras que los tensores normales son inmutables, las variables (tf.Variable) permiten almacenar valores que se pueden modificar, como los pesos de un modelo. Aquí tienes un ejemplo:

In [34]:
# Crear una variable
var = tf.Variable([0.0, 0.0, 0.0])

# Asignar nuevos valores
var.assign([1, 2, 3])
print("Variable actualizada:", var.numpy())

# Incrementar valores de la variable
var.assign_add([1, 1, 1])
print("Variable incrementada:", var.numpy())

# Diferenciación Automática  (Repaso de conceptos)
La diferenciación automática permite calcular derivadas de manera eficiente. Este mecanismo es esencial para entrenar modelos utilizando optimizadores como el descenso de gradiente.

## Calcular derivadas con TensorFlow: Explicación

##  Variables

- En TensorFlow, se usan **variables** (`tf.Variable`) para valores que pueden cambiar y respecto a los cuales queremos derivar.
- Las variables son necesarias para que TensorFlow pueda **rastrear dependencias** y calcular gradientes automáticamente.

---

##  Definir la función

- La función que queremos derivar puede ser cualquier expresión matemática, como un polinomio o la función de pérdida de un modelo.
- Por ejemplo, un polinomio:
$
f(x) = 3x^3 + 2x^2 - 4x - 2
$

- TensorFlow graba las operaciones sobre las variables para poder calcular cómo cada salida depende de sus entradas.

---

##  `tf.GradientTape`

- `GradientTape` es un contexto que **graba todas las operaciones** realizadas sobre variables dentro de su bloque.
- Esto permite a TensorFlow **construir automáticamente un grafo de derivación** para calcular gradientes.

---

##  Calcular el gradiente

- Una vez que la función ha sido evaluada dentro del `GradientTape`, podemos pedir a TensorFlow que calcule la **derivada de la salida respecto a la variable**.
- Matemáticamente, para nuestro polinomio:
$
f'(x) = \frac{d}{dx}(3x^3 + 2x^2 - 4x - 2) = 9x^2 + 4x - 4
$
- Evaluando en $(x = 2)$:

$
f'(2) = 9(2^2) + 4(2) - 4 = 40
$

---

##  Interpretación

- El gradiente obtenido indica **la tasa de cambio de la función respecto a la variable**.
- En aprendizaje automático, esto se usa para **actualizar los parámetros de un modelo** durante el entrenamiento.

---

## Resumen conceptual

1. Se definen **variables** sobre las que queremos derivar.
2. `GradientTape` **graba operaciones** para calcular gradientes automáticamente.
3. `tape.gradient` calcula la **derivada** de la salida respecto a las variables.
4. El resultado es un **tensor que indica la pendiente** de la función en ese punto.
5. Esta técnica se usa ampliamente en **optimización y entrenamiento de redes neuronales**.


In [35]:

def f(x):
    return 3*x**3 + 2*x**2-4*x - 2

In [36]:
#Grafico de dispersión entre a y y donde x
import matplotlib.pyplot as plt
a = tf.linspace(-10, 10, 100)
y = f(a)
plt.scatter(a, y)
plt.show()

# Derivadas de la función

## Función original

$$
f(x) = 3x^3 + 2x^2 - 4x - 2
$$

---

##  Paso 1: Primera derivada

Aplicamos reglas de derivación:

$$
f'(x) = \frac{d}{dx}\left(3x^3 + 2x^2 - 4x - 2\right)
$$

- Derivada de $(3x^3 \;\rightarrow\; 9x^2)$  
- Derivada de $(2x^2 \;\rightarrow\; 4x)$  
- Derivada de $(-4x \;\rightarrow\; -4)$
- Derivada de $(-2 \;\rightarrow\; 0)$  

$$
f'(x) = 9x^2 + 4x - 4
$$

---

##  Paso 2: Segunda derivada

Ahora derivamos otra vez:

$$
f''(x) = \frac{d}{dx}\left(9x^2 + 4x - 4\right)
$$

- Derivada de $(9x^2 \;\rightarrow\; 18x)$  
- Derivada de $(4x \;\rightarrow\; 4)$  
- Derivada de $(-4 \;\rightarrow\; 0)$  

$$
f''(x) = 18x + 4
$$

---

##  Resumen

- **Función original:**

$$
f(x) = 3x^3 + 2x^2 - 4x - 2
$$

- **Primera derivada (pendiente):**

$$
f'(x) = 9x^2 + 4x - 4
$$

- **Segunda derivada (curvatura):**

$$
f''(x) = 18x + 4
$$


##GrandientTape de TensorFlow
Es una cinta de grabación ("tape") que observa todas las operaciones matemáticas realizadas sobre las variables marcadas como tf.Variable.

Luego, podemos pedirle que calcule las derivadas de una expresión con respecto a esas variables.

Se llama "tape" porque funciona como una grabadora:

Graba las operaciones (por ejemplo, multiplicaciones, potencias, sumas...).

Reproduce hacia atrás para aplicar la regla de la cadena y obtener derivadas.


In [37]:
import tensorflow as tf

x = tf.Variable(7.5)

with tf.GradientTape() as tape:
    y = f(x)   # f(x) = x³+....

# Pedimos la derivada de y respecto a x
dy_dx = tape.gradient(y, x)

print("f(x) =", y.numpy())        #
print("f'(x) =", dy_dx.numpy())   #


# Diferencia entre usar GradientTape y luego llamar a tape.gradient

## with tf.GradientTape() as tape:

En el ejemplo anterior creamos la cinta (el “grabador”).

Durante ese bloque, TensorFlow observa todas las operaciones matemáticas que se hacen con variables (tf.Variable).

Es como si grabara paso a paso cómo se calculó la función.

## tape.gradient(y, x)

Una vez finaliza el bloque, usamos esa cinta para pedir la derivada de una salida y respecto a una variable x.

Aquí la cinta reproduce en reversa las operaciones grabadas (regla de la cadena).

Resultado: la derivada numérica en el punto actual de x.

# Primera y segunda derivada

In [38]:

# Definimos la función f(x) = 3x³ + 2x² - 4x - 2
def f(x):
    return 3*x**3 + 2*x**2 - 4*x - 2

# Definimos 'x' como una variable (TensorFlow necesita una Variable para calcular derivadas).
x = tf.Variable(0.481)

# Usamos dos "GradientTape":
# - El primero (tape2) calculará la PRIMERA derivada de f(x) con respecto a x.
# - El segundo (tape) observará lo que hace el primero, para luego calcular la SEGUNDA derivada.

with tf.GradientTape() as tape:
    with tf.GradientTape() as tape2:
        # Evaluamos la función dentro de ambas cintas.
        y = f(x)

    # PRIMERA DERIVADA: f'(x)
    # La primera derivada mide la pendiente de la función en un punto.
    # En términos prácticos: indica la velocidad de cambio de f(x) con respecto a x.
    g_x = tape2.gradient(y, x)

# SEGUNDA DERIVADA: f''(x)
# La segunda derivada mide cómo cambia la pendiente.
# En términos prácticos:
#   - Si f''(x) > 0 → la curva es cóncava hacia arriba (mínimos locales).
#   - Si f''(x) < 0 → la curva es cóncava hacia abajo (máximos locales).
g_x2 = tape.gradient(g_x, x)

print("x =", x.numpy())
print("f(x) =", y.numpy())
print("f'(x) =", g_x.numpy())
print("f''(x) =", g_x2.numpy())


# Quiero Ver las funciones o las ecuaciones de la derivada

In [39]:
import sympy as sp

# Definir la variable simbólica
x = sp.Symbol('x')

# Definir la función
f = 3*x**3 + 2*x**2 - 4*x - 2

# Primera derivada
f_prime = sp.diff(f, x)

# Segunda derivada
f_second = sp.diff(f_prime, x)

print("Función original f(x):", f)
print("Primera derivada f'(x):", f_prime)
print("Segunda derivada f''(x):", f_second)


In [40]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

# Definir la función
def f(x):
    return 3*x**3 + 2*x**2 - 4*x - 2

# Definir el rango de valores para x
x_vals = np.linspace(-3, 3, 200)
f_vals = f(x_vals)

# Usamos TensorFlow para obtener derivadas automáticas
x = tf.Variable(x_vals)

with tf.GradientTape() as tape:
    with tf.GradientTape() as tape2:
        y = f(x)
    f_prime = tape2.gradient(y, x)   # primera derivada
f_second = tape.gradient(f_prime, x) # segunda derivada

# Convertir resultados a numpy para graficar
f_prime_vals = f_prime.numpy()
f_second_vals = f_second.numpy()

# Graficar
plt.figure(figsize=(10,6))
plt.plot(x_vals, f_vals, label="f(x)", linewidth=2)
plt.plot(x_vals, f_prime_vals, label="f'(x)", linestyle="--", linewidth=2)
plt.plot(x_vals, f_second_vals, label="f''(x)", linestyle=":", linewidth=2)

plt.axhline(0, color="black", linewidth=0.7)
plt.axvline(0, color="black", linewidth=0.7)
plt.legend()
plt.title("Función, Primera derivada y Segunda derivada")
plt.xlabel("x")
plt.ylabel("Valor")
plt.grid(True)
plt.show()


##Grafos y funciones

En el contexto de TensorFlow, graph se asocia más comúnmente con gráfos porque describe una secuencia de operaciones que puede ser visualizada o ejecutada. Sin embargo, no se refiere específicamente a una imagen o gráficas de matplotlib o seaborn.

* @tf.function:

Este decorador convierte una función de Python en un gráfo computacional de TensorFlow (un Graph).

Las funciones convertidas con @tf.function son más eficientes porque optimizan las operaciones y permiten ejecutar cálculos en diferentes dispositivos como CPUs, GPUs o TPUs.

* print('Tracing.\n'):

Este mensaje se imprime solo cuando se crea o se "traza" el gráfo computacional por primera vez.
Una vez que el gráfo está trazado, las ejecuciones posteriores de la función no vuelven a imprimir el mensaje porque ya se usa el gráfo optimizado.


* return tf.reduce_sum(x):

Calcula la suma de todos los elementos del tensor x.

tf.reduce_sum es una operación que "reduce" un tensor a un solo valor al aplicar la suma en todas las dimensiones.

**Tracing**
Cuando se llama por primera vez a una función decorada con @tf.function, TensorFlow analiza ("traza") el código para crear un grafo computacional.

Este grafo permite realizar optimizaciones y ejecutar la función de manera más eficiente.

In [41]:
# Decorador de TensorFlow que convierte la función en un "graph function"
# Esto significa que TensorFlow optimiza la ejecución al compilarla en un grafo computacional.
@tf.function
def my_func(x):
    # Este print se ejecutará SOLO la primera vez que TensorFlow "tracea"
    # (construye el grafo de operaciones).
    print('Tracing.\n')

    # tf.reduce_sum suma todos los elementos de x (tensor o array)
    return tf.reduce_sum(x)

In [42]:
x = tf.constant([1, 2, 3])
my_func(x)

In [43]:
my_func(x).numpy()

En llamadas posteriores, TensorFlow solo ejecuta el gráfo optimizado, omitiendo cualquier paso que no sea de TensorFlow. A continuación, observa que my_func no imprime el seguimiento, ya que print es una función de Python, no una función de TensorFlow.

In [44]:
x = tf.constant([10, 9, 8])
my_func(x)

In [45]:
my_func(x).numpy()

Un gráfo puede no ser reutilizable para entradas con una forma diferente (forma y tipo de datos), por lo que se genera un nuevo gráfo en su lugar.

In [46]:
x = tf.constant([10.0, 9.1, 8.2], dtype=tf.float32)
my_func(x)

In [47]:
my_func(x).numpy()

Estos gráfos capturados ofrecen dos beneficios:

1. En muchos casos, proporcionan una aceleración significativa en la ejecución (aunque no en este ejemplo trivial).

2. Puedes exportar estos gráfo, utilizando tf.saved_model, para ejecutarlos en otros sistemas, como un servidor o un dispositivo móvil, sin necesidad de instalar Python.

##Módulos, capas y modelos.

tf.Module es una clase para administrar sus objetos tf.Variable y los objetos tf.function que operan en ellos. La clase tf.Module es necesaria para admitir dos funciones importantes:


Puede guardar y restaurar los valores de sus variables usando tf.train.Checkpoint . Esto es útil durante el entrenamiento, ya que es rápido guardar y restaurar el estado de un modelo.
Puede importar y exportar los valores de tf.Variable y los gráfos de tf.function usando tf.saved_model . Esto le permite ejecutar su modelo independientemente del programa de Python que lo creó.

Aquí hay un ejemplo completo exportando un objeto tf.Module simple

In [48]:
class MyModule(tf.Module):
    """
    Una clase que extiende `tf.Module` para demostrar cómo gestionar variables y funciones en TensorFlow.

    Atributos:
        weight (tf.Variable): Una variable que almacena un valor inicializado durante la creación del módulo.

    Métodos:
        multiply(x):
            Realiza una multiplicación entre la entrada `x` y la variable `weight`.
    """

    def __init__(self, value):
        """
        Constructor de la clase MyModule.

        Args:
            value (float o int): Valor inicial para la variable `weight`.
        """
        self.weight = tf.Variable(value)

    @tf.function
    def multiply(self, x):
        """
        Multiplica la entrada `x` por la variable `weight`.

        Args:
            x (tf.Tensor): Un tensor que representa los valores de entrada.

        Returns:
            tf.Tensor: El resultado de la multiplicación de `x` y `weight`.
        """
        return x * self.weight


 El siguiente código ejecuta una operación de multiplicación elemento por elemento entre el tensor de entrada y el valor almacenado en la variable weight del módulo. En este caso, el resultado es el tensor [3, 6, 9].

1. Creamos una instancia de la clase MyModule con el valor inicial de weight igual a 3. Esto significa que el atributo weight será una variable de TensorFlow (tf.Variable) con un valor inicial de 3.

2. Llamamos al método multiply de la instancia mod pasando un tensor constante de valores [1, 2, 3].



In [49]:
mod = MyModule(3)
mod.multiply(tf.constant([1, 2, 3]))

In [50]:
mod.multiply(tf.constant([1, 2, 3])).numpy()

##Salvar el módulo

Para guardar un módulo en TensorFlow, se usa la función tf.saved_model.save. Este método permite exportar un módulo o modelo de TensorFlow, junto con sus variables y gráficos, para ser reutilizado en otros entornos sin necesidad de depender del programa original de Python.

![image](https://github.com/adiacla/bigdata/blob/master/modulosTF.JPG?raw=true)

In [51]:
save_path = './saved'
tf.saved_model.save(mod, save_path)

El modelo guardado resultante es independiente del código que lo creó. Puede cargar un modelo guardado desde Python, otros enlaces de idioma o TensorFlow Serving . También puede convertirlo para que se ejecute con TensorFlow Lite o TensorFlow JS .

In [52]:
reloaded = tf.saved_model.load(save_path)
reloaded.multiply(tf.constant([4, 5, 6])).numpy()

##Creación de Modelos y Entrenamiento- Bucles de entrenamiento

Ahora vamos a poner todo unido para construir un modelo básico y entrénarlo desde cero.

1. Crear algunos datos de ejemplo. Esto genera una nube de puntos que sigue vagamente una curva cuadrática:

2. Definir modelos personalizados usando tf.keras.Model y entrenarlos manualmente o con utilidades como Model.fit.

Vamos a realizar un ejemplo  de un modelo entrenado para ajustar datos sinteticos o simulados:



In [53]:
# Importa la biblioteca principal de Matplotlib
import matplotlib

# Importa el módulo pyplot de Matplotlib y lo asigna al alias 'plt'
from matplotlib import pyplot as plt

# Configura el tamaño predeterminado de las figuras generadas por Matplotlib
# Esto asegura que todas las gráficas creadas tengan dimensiones de 9 pulgadas de ancho por 6 pulgadas de alto
matplotlib.rcParams['figure.figsize'] = [9, 6]


#Generación de datos aleatorios (sintéticos) a partir de una función

Se genera un conjunto de datos x y se calcula y usando una función cuadrática, a la cual se añade ruido para simular datos experimentales o del mundo real.

* Visualización:
Los puntos (Data) muestran los datos con ruido.

La línea (Ground truth) representa la relación teórica exacta entre x e y sin ruido.

* Leyenda: Facilita identificar qué serie corresponde a los datos simulados y cuál a la función teórica.

Explicaciones del código

1. tf.linspace(-2, 2, 201): Genera 201 puntos equidistantes entre -2 y 2, lo que crea un vector de entradas x.
2. tf.cast(x, tf.float32): Asegura que los valores de x sean del tipo float32 para ser utilizados en operaciones de TensorFlow.
3. Función f(x): Calcula el valor de la ecuación cuadrática $f(x) = x^2 + 2x - 5$ para cada valor en x.
4. tf.random.normal(shape=[201]): Añade ruido aleatorio a los valores de y para simular un conjunto de datos ruidosos.


##plt.plot:
Dibuja dos gráficos, uno con puntos (.) para los datos generados con ruido.
Otro con una línea que representa la función cuadrática sin ruido (la "verdad fundamental").

Al final, el gráfico resultante muestra tanto los datos ruidosos como la función que los genera.


# Creemo un modelo cuadrático paramétrico hecho a mano con Gradiente del descenso (GradientTape)

In [54]:
tf.random.set_seed(42)

# Crear un tensor 'x' con valores en un rango de -2 a 2, dividido en 201 puntos
x = tf.linspace(-2, 2, 201)  # Genera valores de -2 a 2 con 201 puntos equidistantes
# Convertir 'x' a tipo de dato float32 para su procesamiento posterior
x = tf.cast(x, tf.float32)
x.numpy()

In [55]:
# Definir una función f(x) que calcule el valor de la expresión cuadrática: f(x) = x^2 + 2x - 5
def f(x):
    y = x**2 + 2*x - 5  # Evaluación de la función cuadrática
    return y  # Devolver el valor calculado

# Generar el vector de 'y' usando la función f(x) y agregar un ruido aleatorio de media 0 y varianza 1
y = f(x) + tf.random.normal(shape=[201])  # Añadir ruido aleatorio a los valores de 'y'

# Graficar los datos generados (con ruido) usando puntos ('.') en el gráfico
plt.plot(x.numpy(), y.numpy(), '.', label='Data')  # Convertir los tensores a arrays de NumPy para graficar

# Graficar la "verdad fundamental" (la función sin ruido) con una línea continua
plt.plot(x, f(x), label='Ground truth')  # Graficar la función original sin ruido

# Añadir la leyenda para explicar las líneas en el gráfico
plt.legend()  # Mostrar leyenda para identificar los datos y la verdad fundamental


In [56]:
# Preparamos entradas: [x, x^2]
X = tf.stack([x, x**2], axis=1)   # shape = (201, 2)

print("Forma de X:", X.shape)
print("Forma de y:", y.shape)

In [57]:
import pandas as pd

# Create a dictionary with the data
data_dict = {
    'X1': x.numpy(),
    'X2': (x**2).numpy(),
    'y': y.numpy()
}

# Create the pandas DataFrame
df = pd.DataFrame(data_dict)

# Display the first few rows of the DataFrame
display(df.head())

![](https://github.com/adiacla/bigdata/blob/master/perceptron2.jpg?raw=true)

## Creamos un modelo con pesos y bias aleatorios

Veremo como se comparta la función de error si mantenemos constante dos variables y variamos w1. Para explciarl el descenso del gradiente.

**El descenso del gradiente (Gradient Descent)** es un algoritmo de optimización que sirve para encontrar los valores de los parámetros (pesos y sesgos en una red neuronal) que minimizan la función de pérdida.

In [58]:
# Define the fixed values for bias (b) and weight (w1)
b = -5
w2 = 1

# Define a range of values for w2
w1_values = np.linspace(-6, 10, 100)

# Initialize a list to store the mean squared errors
mse_values = []

# Iterate through the w2 values
for w1 in w1_values:
    # Calculate the new column 'a1'
    df['a1'] = b + (w1 * df['X1']) + (w2 * df['X2'])
    # Calculate the mean squared error
    mse = tf.reduce_mean(tf.square(df['a1'] - df['y']))
    mse_values.append(mse.numpy())


# Plot the mean squared error against w2
plt.plot(w1_values, mse_values)
plt.xlabel("w1")
plt.ylabel("Mean Squared Error")
plt.title("Mean Squared Error vs. w2")
plt.show()

In [59]:
df

### Modelo

La salida del modelo para el ejemplo \(i\) es:

$\hat y_i = a1_i = b + w_1 x_{1i} + w_2 x_{2i},\quad \text{con } b=-5,\; w_2=1.$

### Pérdida MSE

La función de pérdida se define como:

$
\mathcal{L}(w_1) = \frac{1}{n}\sum_{i=1}^n \left(b + w_1 x_{1i} + w_2 x_{2i} - y_i\right)^2$

### Derivada de la pérdida respecto a $w_1$

$
\frac{\partial \mathcal{L}}{\partial w_1}
= \frac{2}{n}\sum_{i=1}^n \left(b + w_1 x_{1i} + w_2 x_{2i} - y_i\right)\,x_{1i}
$

### Forma vectorizada

$
\frac{\partial \mathcal{L}}{\partial w_1}
=\frac{2}{n}\, X_1^\top\left(b\,\mathbf{1}+w_1 X_1+w_2 X_2-y\right)
$


In [60]:
#crea dataframe de (w1_values, mse_values
df2 = pd.DataFrame({'w1': w1_values, 'mse': mse_values})
df2

#Un ejemplo dibujando la linea tagente a un punto de la función de pérdida

In [61]:
# Define the fixed values for bias (b) and weight (w2)
b_fixed = tf.constant(-5.0, dtype=tf.float32)
w2_fixed = tf.constant(1.0, dtype=tf.float32)

# Convert DataFrame columns to TensorFlow tensors
X1_tensor = tf.constant(df['X1'].values, dtype=tf.float32)
X2_tensor = tf.constant(df['X2'].values, dtype=tf.float32)
y_tensor = tf.constant(df['y'].values, dtype=tf.float32)


def mse_for_w1(w1):
    """
    Calculates the mean squared error for a given w1, with fixed b and w2.
    """
    a1 = b_fixed + (w1 * X1_tensor) + (w2_fixed * X2_tensor)
    mse = tf.reduce_mean(tf.square(a1 - y_tensor))
    return mse

# Choose the point where w1 = 0
w1_point = tf.constant(0.0, dtype=tf.float32)
mse_point = mse_for_w1(w1_point) # This should be close to 2 based on the previous plot

# Use GradientTape to calculate the gradient of the MSE with respect to w1 at w1_point
with tf.GradientTape() as tape:
    tape.watch(w1_point)
    mse_at_point = mse_for_w1(w1_point)

gradient_at_point = tape.gradient(mse_at_point, w1_point)

print(f"Gradient of MSE at w1 = {w1_point.numpy()}: {gradient_at_point.numpy()}")

# Define the tangent line equation: y = m * (x - x1) + y1
# (x1, y1) = (w1_point.numpy(), mse_point.numpy())
# m = gradient_at_point.numpy()

def tangent_line(w, w1_point, mse_point, gradient):
    return gradient * (w - w1_point) + mse_point

# Generate a range of w1 values for plotting
w1_values_plot = np.linspace(-6, 10, 100)

# Calculate MSE values for plotting
mse_values_plot = [mse_for_w1(tf.constant(w, dtype=tf.float32)).numpy() for w in w1_values_plot]

# Calculate tangent line values for plotting
tangent_values_plot = tangent_line(w1_values_plot, w1_point.numpy(), mse_point.numpy(), gradient_at_point.numpy())

# Plot the MSE curve and the tangent line
plt.figure(figsize=(9, 6))
plt.plot(w1_values_plot, mse_values_plot, label="MSE vs. w1")
plt.plot(w1_values_plot, tangent_values_plot, label=f"Tangent at w1={w1_point.numpy()}", linestyle='--')
plt.scatter([w1_point.numpy()], [mse_point.numpy()], color='red', zorder=5) # Mark the tangent point
plt.xlabel("w1")
plt.ylabel("Mean Squared Error")
plt.title("Mean Squared Error vs. w1 with Tangent Line")
plt.legend()
plt.grid(True)
plt.show()

## Ahora explicado todo entonces vamos Entrenar el modelo usando Tensorflow (con la class Module)

Definición de la clase Model(tf.Module):

**tf.Module** es una clase base para crear modelos personalizados en TensorFlow. Permite realizar un seguimiento automático de las variables y asegura que los parámetros del modelo se traten como variables de TensorFlow.

* Método __init__(self):

*rand_init = tf.random.uniform(shape=[3], minval=0., maxval=5., seed=22)* genera un tensor con 3 valores aleatorios distribuidos uniformemente en el rango [0., 5.].
Estos valores se usarán para inicializar los pesos y el sesgo del modelo.

*self.w_q, self.w_l y self.b * son variables de TensorFlow que se inicializan con estos valores aleatorios.

**self.w_q:** el peso cuadrático correspondiente al término $𝑥2.self.w_l$: el peso lineal correspondiente al término $𝑥.self.b$: el término de sesgo.

**Método __call__(self, x)**:

Este método hace que la clase sea "llamable", es decir, se puede utilizar una instancia de Model como si fuera una función.

Toma un tensor de entrada x y calcula la salida del modelo cuadrático utilizando la fórmula:
$$y = w_q \cdot x^{2} + w_l \cdot x + b$$

donde $w_q$, $w_l$ y  $b$ son los parámetros del modelo.

**Decorador @tf.function:**

El decorador @tf.function convierte el método en un gráfico de TensorFlow, lo que mejora la eficiencia en la ejecución, especialmente cuando se utiliza en GPU o TPU.

Esto optimiza el cálculo, haciéndolo más rápido en llamadas repetidas.

In [62]:
# ============================
# 2. Definimos el modelo con tf.Module
# ============================
class Neurona(tf.Module):
    """
    Una sola neurona: y_pred = w1*x + w2*x^2 + b
    """

    def __init__(self, seed=42):
        # Inicializamos pesos y bias con distribución normal reproducible
        init = tf.random.normal(shape=(2,1), seed=seed)   # 2 entradas -> 1 salida
        self.W = tf.Variable(init)   # Matriz de pesos (2x1)
        self.b = tf.Variable(tf.zeros(1))  # Sesgo

    @tf.function
    def __call__(self, X):
        # Operación de la neurona (sin activación, lineal)
        return tf.matmul(X, self.W) + self.b

##Definir la función de pérdida:

Dado que este modelo está diseñado para predecir valores continuos, el error cuadrático medio (MSE, por sus siglas en inglés) es una buena elección para la función de pérdida. Dado un vector de predicciones, $\hat{y}$ , y un vector de los valores verdaderos o "ground truth", 𝑦, el MSE se define como la media de las diferencias cuadradas entre los valores predichos y los valores reales.

$$
MSE = \frac{1}{m} \sum_{i=1}^{m} (\hat{y}_i - y_i)^2
$$

Donde:
- $ m$ es el número total de muestras.
- $\hat{y}_i$ es la predicción del modelo para la \( i \)-ésima muestra.
- $y_i$ es el valor real o "ground truth" para la \( i \)-ésima muestra.
-$\sum $ denota la sumatoria a lo largo de todas las muestras.

### Detalle del cálculo:

La función `mse_loss` realiza los siguientes pasos:

1. **Diferencia entre predicciones y valores reales:**
   
   $$
   (\hat{y}_i - y_i)
   $$

2. **Cuadrar las diferencias:**
   
   $$
   (\hat{y}_i - y_i)^2
   $$

3. **Promediar las diferencias cuadradas:**

   $$
   MSE = \frac{1}{m} \sum_{i=1}^{m} (\hat{y}_i - y_i)^2
   $$

Este es el cálculo del **MSE**, que mide cuán cerca están las predicciones del modelo de los valores reales.

In [63]:
# ============================
# 3. Función de pérdida y optimización
# ============================
def mse_loss(y_pred, y_true):
    return tf.reduce_mean(tf.square(y_pred - y_true))


##Ciclo de entrenamiento básico para el modelo.

El ciclo hará uso de la función de pérdida MSE y sus gradientes con respecto a la entrada para actualizar iterativamente los parámetros del modelo. El uso de mini-lotes para el entrenamiento proporciona tanto eficiencia de memoria como una convergencia más rápida. La API tf.data.Dataset tiene funciones útiles para dividir en lotes y mezclar los datos.

In [64]:
# ============================
# 4. Entrenamiento con GradientTape
# ============================
# Instanciamos el modelo
modelo = Neurona(seed=42)

# Hiperparámetros
epochs = 200
learning_rate = 0.05
losses = []

for epoch in range(epochs):
    with tf.GradientTape() as tape:
        y_pred = modelo(X)
        loss = mse_loss(y_pred, tf.expand_dims(y, axis=1))  # expandimos y a (201,1)

    # Calculamos gradientes
    grads = tape.gradient(loss, [modelo.W, modelo.b])

    # Actualizamos parámetros (descenso del gradiente manual)
    modelo.W.assign_sub(learning_rate * grads[0])
    modelo.b.assign_sub(learning_rate * grads[1])

    losses.append(loss.numpy())
    if epoch %5 == 0:
        print(f"Epoch {epoch}: Loss = {loss.numpy():.4f}")


# 3. Predecir un valor

El código llama a la función plot_preds, que se utiliza para visualizar las predicciones del modelo y compararlas con los valores reales (y) y las predicciones de la función f (la "verdad base" o el modelo original).

In [65]:
# ============================
# 5. Resultados
# ============================
print("\nPesos aprendidos:")
print("W =", modelo.W.numpy().flatten())
print("b =", modelo.b.numpy())

# Graficamos la evolución de la pérdida
plt.plot(losses)
plt.xlabel("Época")
plt.ylabel("MSE")
plt.title("Entrenamiento de una sola neurona")
plt.show()

# Graficamos la predicción vs datos
plt.scatter(x, y, label="Datos con ruido", s=10)
plt.plot(x, f(x), label="Función real", linewidth=2)
plt.plot(x, modelo(X), label="Modelo entrenado", linewidth=2, linestyle="--")
plt.legend()
plt.show()

In [66]:
# ============================
# 5. Resultados
# ============================
print("\nPesos aprendidos:")
print("W =", modelo.W.numpy().flatten())
print("b =", modelo.b.numpy())

# Graficamos la evolución de la pérdida
plt.plot(losses)
plt.xlabel("Época")
plt.ylabel("MSE")
plt.title("Entrenamiento de una sola neurona")
plt.show()

# Graficamos la predicción vs datos
plt.scatter(x, y, label="Datos con ruido", s=10)
plt.plot(x, f(x), label="Función real", linewidth=2)
plt.plot(x, modelo(X), label="Modelo entrenado", linewidth=2, linestyle="--")
plt.legend()
plt.show()

#Keras

El modelo quedó entrenado y tiene buenos resultados, pero podemos hacer las implementaciones de utilidades de manera más fácil y sencilla usnado utilidades comunes de entrenamiento están disponibles en el módulo tf.keras.

Por lo tanto vamos a considera utilizar esas funciones en la siguiente sección antes de escribir las propias, como hicimos anteriormente.



**Keras** es una interfaz de alto nivel para TensorFlow, diseñada para facilitar y agilizar la implementación de soluciones de aprendizaje automático (ML), con un enfoque principal en el aprendizaje profundo.

Esta biblioteca cubre todo el flujo de trabajo de ML, desde la preparación de datos hasta la implementación del modelo, pasando por el ajuste de hiperparámetros. Su principal objetivo es permitir una experimentación rápida y eficiente.


Con Keras, se obtiene acceso completo a la escalabilidad y las capacidades multidispositivo de TensorFlow. Es posible ejecutar modelos en dispositivos potentes como TPUs o clusters de GPU, y también exportar modelos entrenados para su uso en navegadores web o dispositivos móviles. Además, Keras ofrece la posibilidad de desplegar modelos como APIs web.


El diseño de Keras está orientado a reducir la carga cognitiva, enfocándose en los siguientes aspectos:


1. Proporcionar interfaces simples y consistentes.
2. Minimizar la cantidad de pasos necesarios para realizar tareas comunes.
3. Ofrecer mensajes de error claros y fáciles de entender.
4. Seguir el principio de "divulgación progresiva de complejidad", donde el usuario puede comenzar fácilmente y aprender gradualmente a medida que avanza en tareas más complejas.
5. Fomentar la escritura de código conciso y legible.


**Utilizar Keras**

Cualquier persona que utilice TensorFlow debería hacerlo a través de la API de Keras. Ya sea un ingeniero, un investigador o un profesional del aprendizaje automático, Keras es la opción recomendada para comenzar.


Existen casos específicos, como la creación de herramientas sobre TensorFlow o el desarrollo de plataformas de alto rendimiento personalizadas, donde puede ser necesario utilizar las APIs de bajo nivel de TensorFlow. Sin embargo, para la mayoría de los usuarios, Keras será la opción preferida.


**Componentes principales de Keras**

Keras está basado en dos estructuras de datos clave:
*capas y modelos*. Una **capa** es una función que realiza una transformación entre las entradas y las salidas, mientras que un **modelo** es un gráfico acíclico dirigido (DAG) de capas.

##Capas

La clase *tf.keras.layers.Layer* es la piedra angular de Keras. Cada capa encapsula un conjunto de pesos y realiza ciertos cálculos a través del método call. Los pesos que se crean pueden ser entrenables o no, y las capas pueden estar compuestas de manera recursiva. Es decir, una capa puede contener otras capas como atributos, permitiendo que la capa externa gestione los pesos de las capas internas.

Además, las capas pueden utilizarse para tareas de preprocesamiento, como normalización de datos o vectorización de texto. Estas capas de preprocesamiento pueden integrarse directamente en el modelo, permitiendo su portabilidad tanto durante como después del entrenamiento.

##Modelos

Un modelo es un objeto que agrupa capas y que puede ser entrenado con datos. El tipo de modelo más sencillo es el modelo secuencial, que organiza las capas en una pila lineal. Para arquitecturas más complejas, Keras permite utilizar la API funcional, que facilita la creación de gráficos arbitrarios de capas, o incluso escribir modelos completamente personalizados utilizando subclases.


La clase *tf.keras.Model* proporciona métodos integrados para entrenar y evaluar modelos:

***fit***: Entrena el modelo durante un número determinado de épocas.

***predict***: Genera predicciones a partir de las entradas.

***evaluate***: Devuelve la pérdida y las métricas del modelo, configuradas a través del método compile.

Estos métodos ofrecen acceso a varias funcionalidades útiles durante el entrenamiento:

***Callbacks:*** Permiten detener el entrenamiento anticipadamente, establecer puntos de control del modelo y monitorear el proceso mediante TensorBoard. También es posible implementar callbacks personalizados.


***Entrenamiento distribuido:*** Keras facilita la extensión del entrenamiento a múltiples GPUs, TPUs o dispositivos.

***Fusión escalonada:*** Al configurar steps_per_execution en compile, se pueden procesar varios lotes en una sola llamada de tf.function, mejorando la utilización del dispositivo, especialmente en TPUs.

Para más detalles sobre cómo utilizar el método fit, consulta la guía de entrenamiento y evaluación. Si deseas personalizar el ciclo de entrenamiento y evaluación, puedes consultar la sección sobre personalización de fi().

###Otras herramientas y APIs de Keras

Keras ofrece una variedad de APIs y herramientas adicionales para el aprendizaje profundo, entre las que se incluyen:

* Optimizadores
* Métricas
* Funciones de pérdida
* Utilidades para la carga de datos

Estas herramientas complementan la experiencia de entrenamiento y son fundamentales para optimizar y evaluar modelos de aprendizaje profundo.



Vamos a realizar el ejercicio que hicimos en Tensorflow donde modelamos nuestras propias funciones para usar Keras.


Empecemos creando un Modelo Secuencial en Keras utilizando tf.keras.Sequential. Una de las capas más simples de Keras es la capa densa (Dense), que se puede instanciar con tf.keras.layers.Dense. La capa densa es capaz de aprender relaciones lineales multidimensionales de la forma  $𝑌=𝑊𝑋+𝑏$. Para aprender una ecuación no lineal de la forma $𝑤_1𝑥^2+𝑤_2𝑥+𝑏$​, la entrada de la capa densa debe ser una matriz de datos con $𝑥^2$  y $x$ como características.

La capa lambda *tf.keras.layers.Lambda* se puede usar para realizar esta transformación de apilamiento.


1. La primera capa es una capa Lambda. Esta capa aplica una transformación personalizada sobre los datos.
En este caso, estamos apilando dos características: $'x'$ y $'x^2$' a lo largo del eje 1 (columnas) utilizando tf.stack.
Esto permite que el modelo reciba como entrada tanto $x$ como $x^2$, lo cual es útil para aprender relaciones no lineales.

2. La siguiente capa es una capa densa (Dense). Esta capa realizará una combinación lineal de las entradas que recibe.
'units=1' significa que la capa tendrá una sola unidad de salida (un solo valor de predicción).
'kernel_initializer=tf.random.normal' inicializa los pesos de la capa de forma aleatoria usando una distribución normal.



In [67]:
data = np.column_stack((x.numpy(), (x.numpy()**2),y.numpy()))
data

## Declaración de la red

### Lambda layer:

Toma la entrada x y la transforma en un vector [x, x²].

Es decir, pasa de tener 1 característica → 2 características.

Dense(units=1):

Esto es una capa densa con 1 neurona.

Esa neurona recibe las 2 entradas (x y x²) y calcula:

$𝑦=𝑤1⋅𝑥+𝑤2⋅𝑥2+𝑏$

Es un modelo lineal en 2 variables (pero no hay función de activación, así que la salida es lineal).

In [68]:
modelo_keras = tf.keras.Sequential([
    tf.keras.layers.Lambda(lambda x: tf.stack([x, x**2], axis=1)),
    tf.keras.layers.Dense(
        units=1,
        kernel_initializer=tf.keras.initializers.RandomNormal(seed=42),  # kernel reproducible
    )
])


In [69]:
modelo_keras.summary()

In [70]:
# Compilamos el modelo con una función de pérdida MSE (error cuadrático medio) y un optimizador SGD con tasa de aprendizaje de 0.01.
modelo_keras.compile(
    loss=tf.keras.losses.MSE,
    optimizer=tf.keras.optimizers.SGD(learning_rate=0.01)
)

In [71]:
# Entrenamos el modelo durante 100 épocas con un tamaño de lote de 32, utilizando los datos de entrada x y las etiquetas y.
history = modelo_keras.fit(x, y, epochs=100, batch_size=32, verbose=1)




In [72]:
# Guardamos el modelo entrenado en un archivo para su uso posterior.
modelo_keras.save('./modelo_keras.keras')

In [73]:
modelo_keras.summary()

Vamos a predecir un conjunto de valores

In [74]:
# Realizamos predicciones utilizando el modelo entrenado con los datos de entrada x.
predicciones = modelo_keras.predict(x)

# Las predicciones son una lista de valores de salida generados por el modelo.


In [75]:
predicciones

In [76]:
  # Graficar los datos reales (con ruido) usando puntos
  plt.plot(x, y, '.', label='Data')  # 'x' es la entrada y 'y' son los datos generados con ruido

  # Graficar la "verdad fundamental" (la función sin ruido) con una línea
  plt.plot(x, f(x), label='Ground truth')  # 'f(x)' es la función cuadrática original sin ruido

  # Graficar las predicciones del modelo usando una línea
  plt.plot(x, predicciones, label='Predictions')  #son las predicciones del modelo entrenado

  # Añadir un título al gráfico
  plt.title("Modelo entrenado con Keras")  # El título se pasa como argumento a la función

  # Mostrar la leyenda para identificar las diferentes líneas
  plt.legend()
